spring:
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b206.p.ssafy.io:3306/wooahan?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: wooahan
    password: penguin
  # JPA ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 658207955186-n84qpvfhtdi82n6mfvbmh6v99aevulv7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
oauth2:
  google:
      client-id: 658207955186-n84qpvfhtdi82n6mfvbmh6v99aevulv7.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://k8b206.p.ssafy.io/api/login/oauth2/code/google
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 9090
