spring:
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b206.p.ssafy.io:3306/wooahan?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: wooahan
    password: penguin
  # JPA ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 658207955186-n84qpvfhtdi82n6mfvbmh6v99aevulv7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
#          kakao:
#            client-id: 	1e97e6076ee6e76cefd39481410cdab5
#            client-secret: 7R0KJXIi8UoqYIhDSE7fpBNJzyUW7iat
#            client-name : Kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: https://k8b206.p.ssafy.io/api/login/oauth2/code/kakao
#        provider :
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
oauth2:
  google:
      client-id: 658207955186-n84qpvfhtdi82n6mfvbmh6v99aevulv7.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: https://k8b206.p.ssafy.io/api/login/oauth2/code/state/google
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  config:
    classpath:
      log4j2.yml

server:
  port: 9090
