import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { game } from "api/game";

export const getQuizData = createAsyncThunk(
  "sleigh/getQuizData",
  (difficulty) => game.get.run(difficulty)
);

const initialState = {
  quizData: [],
  status: "idle",
};

export const sleighSlice = createSlice({
  name: "sleigh",
  initialState,
  reducers: {
    setStage: (state, action) => {
      state.stageLevel = action.payload;
    },
    setIsStart: (state, action) => {
      state.isStart = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getQuizData.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getQuizData.fulfilled, (state, action) => {
        state.status = "idle";
        state.quizData = action.payload;
      })
      .addCase(getQuizData.rejected, (state, action) => {
        state.status = "error";
      });
  },
});

export const sleighActions = sleighSlice.actions;

export default sleighSlice.reducer;
